const escA=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const statusA={awaiting_store_confirmation:['بانتظار المتجر','gold'],store_confirmed:['تم تأكيد الطلب','green'],processing:['قيد التجهيز','blue'],shipped:['تم الشحن','blue'],delivered:['تم التسليم','green'],completed:['تم التسليم','green'],store_rejected:['أُلغي الطلب','red'],store_cancelled:['أُلغي الطلب وأُعيدت المنتجات','red'],restored:['عادت المنتجات إلى السلة','green'],needs_review:['قيد المراجعة','orange']};
const terminalA=new Set(['completed','delivered','store_cancelled','store_rejected','restored','closed']);
const badgeA=s=>{const x=statusA[s]||['قيد المتابعة','muted'];return `<span class="badge ${x[1]}">${x[0]}</span>`};
const moneyA=(n,c='EGP')=>`${Number(n||0).toFixed(2)} ${escA(c)}`;
const stateA=r=>{const restoration=(r.store_order_cart_restorations||[])[0];if(restoration&&restoration.status==='restored')return 'restored';return r.status||'awaiting_store_confirmation'};
const dateA=v=>{try{return new Date(v).toLocaleDateString('ar-EG',{year:'numeric',month:'short',day:'numeric'})}catch(_){return ''}};
function cartSnapshot(){try{return JSON.parse(localStorage.getItem('elan_cart')||'[]').reduce((n,x)=>n+(Number(x.q)||0),0)}catch(_){return 0}}
function updateCartShortcut(restored=0){const el=document.querySelector('#cartShortcut');if(!el)return;el.querySelector('b').textContent=cartSnapshot();el.classList.toggle('has-restored',restored>0);el.querySelector('span').textContent=restored?`السلة · ${restored} مسترجع`:'سلة Élan Scents'}
function requestLine(r){const state=stateA(r),items=r.store_order_request_items||[],names=items.slice(0,2).map(i=>`${escA(i.product_name)}${Number(i.quantity)>1?` × ${i.quantity}`:''}`).join('، ');return `<article class="compact-order"><div class="compact-order-main"><div><span class="order-store">${escA(r.stores&&r.stores.name||'متجر')}</span><h3>${escA(r.tracking_number)}</h3><p>${names||'تفاصيل المنتجات متاحة داخل الطلب'}${items.length>2?` <span class="muted">+${items.length-2} أخرى</span>`:''}</p></div><div class="compact-order-side">${badgeA(state)}<strong>${moneyA(r.total_amount??r.subtotal,r.currency)}</strong></div></div><div class="compact-order-foot"><span>${dateA(r.created_at)}</span><details><summary>التفاصيل</summary><div class="order-detail">${items.map(i=>`<div><span>${escA(i.product_name)} × ${i.quantity}</span><b>${moneyA(i.line_total,i.currency)}</b></div>`).join('')}<hr><div><span>المتجر</span><b>${escA(r.stores&&r.stores.name||'—')}</b></div><div><span>رقم التتبع</span><b>${escA(r.tracking_number)}</b></div></div></details></div></article>`}
function sessionRequests(s){return s.store_order_requests||[]}
function flatten(sessions){return sessions.flatMap(s=>sessionRequests(s).map(r=>({...r,session:s})))}
function renderList(el,requests,empty){el.innerHTML=requests.length?requests.map(requestLine).join(''):`<div class="empty">${empty}</div>`}
function fillYears(sessions){const select=document.querySelector('#archiveYear');const years=[...new Set(sessions.map(s=>new Date(s.created_at).getFullYear()).filter(Number.isFinite))].sort((a,b)=>b-a);select.innerHTML='<option value="">كل السنوات</option>'+years.map(y=>`<option value="${y}">${y}</option>`).join('')}
function renderAccount(sessions){const requests=flatten(sessions),active=requests.filter(r=>!terminalA.has(stateA(r))),completed=requests.filter(r=>['completed','delivered'].includes(stateA(r))).sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));const restored=requests.filter(r=>stateA(r)==='restored').length;document.querySelector('#ordersCount').textContent=`${requests.length} طلب`;document.querySelector('#stats').innerHTML=[['قيد المتابعة',active.length,'orange'],['تم التسليم',completed.length,'green'],['مسترجعة',restored,'blue']].map(x=>`<div class="stat ${x[2]}"><small>${x[0]}</small><b>${x[1]}</b></div>`).join('');renderList(document.querySelector('#activeOrders'),active,'لا توجد طلبات حالية تحتاج متابعة');renderList(document.querySelector('#recentOrders'),completed.slice(0,5),'لا توجد طلبات مكتملة بعد');fillYears(sessions);document.querySelector('#archiveOrders').hidden=true;updateCartShortcut(restored);window.__customerSessions=sessions}
async function fetchSessions(params=''){const r=await fetch(`/api/customer-orders${params}`,{headers:Portal.auth()});const d=await r.json();if(!r.ok)throw Error(d.error||'تعذر تحميل الطلبات');return d.sessions||[]}
async function loadArchive(e){e&&e.preventDefault();const q=encodeURIComponent(document.querySelector('#archiveSearch').value.trim()),year=document.querySelector('#archiveYear').value;const params=[];if(q)params.push(`q=${q}`);if(year)params.push(`year=${encodeURIComponent(year)}`);const sessions=await fetchSessions(params.length?`?${params.join('&')}`:'');const requests=flatten(sessions).filter(r=>terminalA.has(stateA(r)));const box=document.querySelector('#archiveOrders');box.hidden=false;renderList(box,requests,'لا توجد طلبات مطابقة للبحث')}
async function loadAccount(){if(!Portal.session())return;document.querySelector('#login').hidden=true;document.querySelector('#app').hidden=false;document.querySelector('#logout').hidden=false;renderAccount(await fetchSessions())}
document.querySelector('#loginForm').addEventListener('submit',async e=>{e.preventDefault();try{await Portal.login(e.target);await loadAccount()}catch(err){document.querySelector('#message').textContent=err.message}});document.querySelector('#archiveForm').addEventListener('submit',e=>loadArchive(e).catch(err=>{document.querySelector('#message').textContent=err.message}));if(Portal.session())loadAccount().catch(e=>document.querySelector('#message').textContent=e.message);setInterval(()=>{if(Portal.session())loadAccount().catch(()=>{})},30000);
