var XBTN='<button class="mx" aria-label="close"><svg viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="url(#gg)" stroke-width="2" stroke-linecap="round"><path d="M5 5l14 14M19 5L5 19"/></svg></button>';
var LOGO='<a class="mlogo" href="#"><div class="logo"><div><b class="gold en">Élan</b> <span class="en">Scents</span></div><small class="en">THE HOME OF GULF FRAGRANCES</small><i></i></div></a>';
var lang='ar',P=[],F={},V;
function setViewportUnit(){document.documentElement.style.setProperty('--app-vh',(window.visualViewport?window.visualViewport.height:window.innerHeight)*.01+'px')}
setViewportUnit();addEventListener('resize',setViewportUnit,{passive:true});if(window.visualViewport)visualViewport.addEventListener('resize',setViewportUnit,{passive:true});
var PERFUMES=[];
var LB={ar:{home:'الرئيسية',s:'ابحث عن عطر أو براند',all:'الكل',cat:'الفئة',br:'البراند',st:'المتجر',oc:'المناسبة',nt:'النوتة',pmin:'السعر من',pmax:'السعر إلى',so:['الأكثر صلة','الأحدث','السعر: من الأقل','السعر: من الأعلى'],none:'لا توجد عطور متاحة حاليًا وفق بيانات المتاجر',all2:'كل العطور',inf:'معلومات المتجر',bs:'العلامات المتاحة',more:'متاجر أخرى',det:'عرض التفاصيل',added:'أضيف إلى العربة',availq:'المتاح حاليًا: ',only:' فقط.',qty:'الكمية',add:'أضف إلى العربة',desc:'الوصف',comp:'التركيب العطري',notes:'النفحات',rel:'منتجات مرتبطة',size:'الحجم',unav:'غير متاح',total:'الإجمالي',taxnote:'تفاصيل الضرائب والشحن تظهر قبل إتمام الشراء وفقًا لقواعد المتجر.',checkout:'إتمام الشراء (قريبًا)',incTax:'السعر شامل الضريبة',excTax:'السعر غير شامل الضريبة',incShip:'شامل الشحن',excShip:'غير شامل الشحن'},
en:{home:'Home',s:'Search a perfume or brand',all:'All',cat:'Category',br:'Brand',st:'Store',oc:'Occasion',nt:'Note',pmin:'Min price',pmax:'Max price',so:['Most relevant','Newest','Price: low to high','Price: high to low'],none:'No fragrances currently available per store data',all2:'All fragrances',inf:'Store information',bs:'Available brands',more:'more stores',det:'View details',added:'Added to cart',availq:'Currently available: ',only:' only.',qty:'Quantity',add:'Add to cart',desc:'Description',comp:'Composition',notes:'Notes',rel:'Related fragrances',size:'Size',unav:'Unavailable',total:'Total',taxnote:'Tax and shipping details are shown before checkout, per the store rules.',checkout:'Checkout (soon)',incTax:'Price includes tax',excTax:'Price excludes tax',incShip:'Shipping included',excShip:'Shipping not included'}};
var CFG={waNumber:'',email:'',phone:'',endpoint:'',orderEndpoint:'',social:{facebook:'',instagram:'',tiktok:''},stores:{'Afnan Egypt':{base:'https://egypt.afnan.com',key:''},'Emarati Scents':{base:'https://emaratiscents.com',key:''}}};
function ingest(store,items){items.forEach(function(r){var b=BR.filter(function(x){return x.toLowerCase()==String(r.brand).toLowerCase()})[0];if(!b)return;var p=PERFUMES.filter(function(x){return x.id==r.id})[0];if(!p){p={id:r.id,name:r.name,brand:b,category:r.category,occasion:r.occasion,notes:r.notes||[],ind:r.ind||[],rel:r.rel,ts:r.ts,offers:[]};PERFUMES.push(p)}p.offers=p.offers.filter(function(o){return o.store!=store});p.offers.push({store:store,price:r.price,cur:r.cur,avail:!!r.avail,flags:r.flags||[]})});refreshAll()}
function refreshAll(){render();if(P.length)view()}
function counts(){var b={},st={},n=0;PERFUMES.forEach(function(p){if(best(p)){n++;b[p.brand]=1}p.offers.forEach(function(o){if(o.avail)st[o.store]=1})});document.getElementById('cbn').textContent=BR.length;document.getElementById('csn').textContent=ST.length;document.getElementById('cnt').textContent=n}
var IND={ar:{featured:'الأكثر تميزًا',rating:'الأعلى تقييمًا',sales:'الأكثر مبيعًا',views:'الأكثر مشاهدة',searches:'الأكثر بحثًا',demand:'الأكثر طلبًا',topBrand:'أشهر عطور كل براند'},en:{featured:'Most distinguished',rating:'Top rated',sales:'Best sellers',views:'Most viewed',searches:'Most searched',demand:'Most requested',topBrand:'Top of each brand'}};
function chips(){var have={};PERFUMES.forEach(function(p){(p.ind||[]).forEach(function(k){have[k]=1})});var ks=Object.keys(IND[lang]).filter(function(k){return have[k]});return '<div class="strip" style="padding:4px 0 8px">'+(ks.length?ks.map(function(k){return '<button class="btn" data-ind="'+k+'" style="flex:none;padding:8px 14px;font-size:12px">'+IND[lang][k]+'</button>'}).join(''):'<div class="empty">'+T().indNone+'</div>')+'</div>'}
document.addEventListener('click',function(e){var c=e.target.closest('[data-ind]');if(c){F.ind=F.ind==c.dataset.ind?'':c.dataset.ind;results()}});
function catBlocks(){var t=T(),imgs=['/assets/cards/category-men.webp','/assets/cards/category-women.webp','/assets/cards/category-unisex.webp'];return sec('cats')[3].map(function(n,i){return '<div class="cb"><div class="card wide art" data-go="col|cats|'+i+'"><div class="artbg"><img src="'+imgs[i]+'" alt="" loading="lazy"></div><h4 style="font-family:El Messiri,sans-serif;font-size:24px">'+n+'</h4><small>'+t.ctag[i]+'</small><span class="st">'+t.view+'</span></div></div>'}).join('')}
function masterBlock(){var t=T();return '<div class="cb"><div class="card msel" data-go="sec|master" role="img" aria-label="Élan Scents Selections"></div><span class="sub" data-go="sec|master">'+t.view+'</span><div class="strip">'+strip('master')+'</div></div>'}
function esc(s){return String(s==null?'':s).replace(/[&<>"]/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]})}
function ratingHTML(r){r=+r||0;if(!r)return '';var stars='';for(var i=1;i<=5;i++)stars+='<span class="'+(i<=Math.round(r)?'on':'')+'">★</span>';return '<div class="rating" aria-label="'+r.toFixed(1)+' / 5"><span class="stars" aria-hidden="true">'+stars+'</span><b>'+r.toFixed(1)+'</b></div>'}
var CARTSVG='<svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="url(#gg)" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><circle cx="9" cy="20" r="1"/><circle cx="17" cy="20" r="1"/><path d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z"/></svg>';
function byId(i){return PERFUMES.filter(function(q){return q.id==i})[0]}
function nmOf(k,i){var a=sec(k);return a&&a[3]?a[3][i]:''}
function pc(x){var p=x.p,b=x.b,l=LB[lang],t=T();
var img=p.img?'<img src="'+p.img+'" alt="" loading="lazy">':'<div class="ph" style="width:70%"></div>';
var cat=(p.cats||[]).slice(0,1).map(function(i){return nmOf('cats',i)}).join('');
var rating=ratingHTML(p.rating);
var occ=(p.occs||[]).slice(0,2).map(function(i){return '<span class="tg">'+nmOf('occ',i)+'</span>'}).join('');
return '<div class="card pf" data-go="prod|'+p.id+'"><div class="pim">'+img+'</div><h4>'+(p.pn||p.name)+(p.sz?' <small>\u00b7 '+p.sz+'</small>':'')+'</h4><small>'+p.brand+(cat?' \u00b7 '+cat:'')+'</small>'+rating+(p.sd?'<p class="sd">'+p.sd+'</p>':'')+(occ?'<div class="tgs">'+occ+'</div>':'')+(b?'<div class="pr"><span class="price">'+b.price+' '+(b.cur||'')+'</span><small>'+b.store+'</small></div>':'<span class="st">'+t.soon+'</span>')+'<div class="act"><span class="vd">'+l.det+'</span>'+(b?'<button class="cartb" data-add="'+p.id+'" aria-label="cart">'+CARTSVG+'</button>':'')+'</div></div>'}
var SP_BY_ID={};var CART=[];try{CART=JSON.parse(localStorage.getItem('elan_cart')||'[]')}catch(e){}var CART_SYNCING=false,CART_PULLING=false,CART_FIRST_SYNC_DONE=false,CART_LOCAL_DIRTY=false,CART_PUSH_QUEUED=false,CART_REV=0,GUEST_CART_SYNCING=false,GUEST_SAVE_QUEUED=false;
function authUserId(){return AUTH&&AUTH.user&&AUTH.user.id||''}
function authHeaders(){return{apikey:SB.key,Authorization:'Bearer '+(AUTH&&AUTH.access_token||SB.key),'Content-Type':'application/json'}}
function storeProductIdFor(sid){var p=byId(sid),b=p&&best(p);return b&&b.storeProductId||''}
function sidForStoreProduct(id){var found='';PERFUMES.some(function(p){return p.offers.some(function(o){if(String(o.storeProductId)==String(id)){found=p.id;return true}return false})});if(!found){var sid=SP_BY_ID[String(id)];if(sid&&byId(sid))found=sid}return found}
async function pushCartToCloud(){var uid=authUserId();if(!uid||!SB.url||!SB.key)return;if(CART_SYNCING||CART_PULLING){CART_PUSH_QUEUED=true;return}CART_SYNCING=true;var revision=CART_REV,snapshot=CART.map(function(c){return{sid:c.sid,q:c.q}});try{var h=authHeaders(),del=await fetch(SB.url+'/rest/v1/cart_items?user_id=eq.'+encodeURIComponent(uid),{method:'DELETE',headers:h});if(!del.ok)return;var rows=snapshot.map(function(c){return{user_id:uid,store_product_id:storeProductIdFor(c.sid),quantity:Math.max(1,+c.q||1)}}).filter(function(x){return x.store_product_id});if(rows.length){var saved=await fetch(SB.url+'/rest/v1/cart_items',{method:'POST',headers:Object.assign({},h,{Prefer:'return=minimal'}),body:JSON.stringify(rows)});if(!saved.ok)return}if(CART_REV===revision)CART_LOCAL_DIRTY=false;else CART_PUSH_QUEUED=true}catch(e){}finally{CART_SYNCING=false;if(CART_PUSH_QUEUED){CART_PUSH_QUEUED=false;setTimeout(pushCartToCloud,0)}}}
async function syncCartFromCloud(mergeLocal){var uid=authUserId();if(!uid||!SB.url||!SB.key||CART_PULLING||CART_SYNCING)return;if(CART_LOCAL_DIRTY&&!mergeLocal)return;CART_PULLING=true;var revision=CART_REV;try{var r=await fetch(SB.url+'/rest/v1/cart_items?user_id=eq.'+encodeURIComponent(uid)+'&select=store_product_id,quantity',{headers:authHeaders()});if(!r.ok)return;var rows=await r.json(),cloud={},unmapped=false;rows.forEach(function(x){var sid=sidForStoreProduct(x.store_product_id);if(!sid){unmapped=true;return}cloud[sid]=Math.max(cloud[sid]||0,+x.quantity||1)});if((unmapped&&!PERFUMES.length)||revision!==CART_REV)return;if(mergeLocal)CART.forEach(function(c){if(c.sid)cloud[c.sid]=Math.max(cloud[c.sid]||0,+c.q||1)});CART=Object.keys(cloud).map(function(sid){return{sid:sid,q:cloud[sid]}});try{localStorage.setItem('elan_cart',JSON.stringify(CART))}catch(e){}cartBadge();CART_FIRST_SYNC_DONE=true;CART_LOCAL_DIRTY=!!mergeLocal;CART_PULLING=false;if(mergeLocal)await pushCartToCloud()}catch(e){}finally{CART_PULLING=false}}
async function saveGuestCartToCloud(){if(AUTH||!window.GuestIdentity||!GuestIdentity.enabled())return;if(GUEST_CART_SYNCING){GUEST_SAVE_QUEUED=true;return}GUEST_CART_SYNCING=true;try{await GuestIdentity.save(CART.map(function(c){return{sid:c.sid,storeProductId:storeProductIdFor(c.sid),q:c.q}}))}catch(e){}finally{GUEST_CART_SYNCING=false;if(GUEST_SAVE_QUEUED){GUEST_SAVE_QUEUED=false;setTimeout(saveGuestCartToCloud,0)}}}
async function syncGuestCartFromCloud(){if(GUEST_CART_SYNCING||AUTH||!window.GuestIdentity||!GuestIdentity.enabled()||!PERFUMES.length)return;GUEST_CART_SYNCING=true;try{var result=await GuestIdentity.resolve();if(!result||!Array.isArray(result.cart))return;var cloud={};result.cart.forEach(function(row){var sid=row.sid||sidForStoreProduct(row.storeProductId);if(sid)cloud[sid]=Math.max(cloud[sid]||0,+row.q||1)});CART.forEach(function(row){if(row.sid)cloud[row.sid]=Math.max(cloud[row.sid]||0,+row.q||1)});CART=Object.keys(cloud).map(function(sid){return{sid:sid,q:cloud[sid]}});try{localStorage.setItem('elan_cart',JSON.stringify(CART))}catch(e){}cartBadge();await GuestIdentity.save(CART.map(function(c){return{sid:c.sid,storeProductId:storeProductIdFor(c.sid),q:c.q}}))}catch(e){}finally{GUEST_CART_SYNCING=false;if(GUEST_SAVE_QUEUED){GUEST_SAVE_QUEUED=false;setTimeout(saveGuestCartToCloud,0)}}}
function saveCart(){CART_REV++;CART_LOCAL_DIRTY=true;try{localStorage.setItem('elan_cart',JSON.stringify(CART))}catch(e){}cartBadge();if(authUserId())pushCartToCloud();else saveGuestCartToCloud()}
function cartBadge(){var n=CART.reduce(function(a,c){return a+c.q},0),b=document.querySelector('button[data-sheet="cart"]');if(b)b.setAttribute('data-n',n)}
function cartPulse(){var b=document.querySelector('button[data-sheet="cart"]');if(!b)return;b.classList.remove('cart-pulse');void b.offsetWidth;b.classList.add('cart-pulse');setTimeout(function(){b.classList.remove('cart-pulse')},650)}
function toast(m){var e=document.getElementById('toast');e.textContent=m;e.className='show';clearTimeout(toast.t);toast.t=setTimeout(function(){e.className=''},2600)}
function addToCart(sid,q){var p=byId(sid),b=p&&best(p),l=LB[lang];if(!b)return toast(l.unav);var it=CART.filter(function(c){return c.sid==sid})[0],want=(it?it.q:0)+(q>0?q:1),msg=l.added;if(b.stock!=null&&want>b.stock){want=b.stock;msg=l.availq+b.stock+l.only}if(want<1)return toast(l.unav);if(it)it.q=want;else CART.push({sid:sid,q:want});saveCart();cartPulse();toast(msg)}
function cartQty(s){var a=s.split('|'),it=CART.filter(function(c){return c.sid==a[0]})[0];if(!it)return;var p=byId(a[0]),b=p&&best(p),n=it.q+(+a[1]),l=LB[lang];if(n<1)n=1;if(b&&b.stock!=null&&n>b.stock){n=b.stock;toast(l.availq+b.stock+l.only)}it.q=n;saveCart();sheet('cart')}
function cartDel(sid){CART=CART.filter(function(c){return c.sid!=sid});saveCart();sheet('cart')}
var ORDER_UI={ar:{execute:'تنفيذ الطلب',orderTitle:'بيانات تنفيذ الطلب',orderNo:'رقم الطلب',name:'الاسم الكامل',phone:'رقم الهاتف',email:'البريد الإلكتروني',address:'عنوان التوصيل',notes:'ملاحظات إضافية',confirm:'إرسال طلب المتجر',back:'العودة للسلة',sent:'تم تسجيل الطلب وإرسال إشعاره',saved:'تم حفظ الطلب لحين ربط قناة الإشعارات',pending:'بانتظار تأكيد المتجر',subtotal:'إجمالي المنتجات',store:'المتجر',required:'يرجى استكمال البيانات'},en:{execute:'Place store order',orderTitle:'Order details',orderNo:'Order number',name:'Full name',phone:'Phone number',email:'Email',address:'Delivery address',notes:'Additional notes',confirm:'Send store order',back:'Back to cart',sent:'The order was registered and its notification was sent',saved:'The order was saved until a notification channel is connected',pending:'Awaiting store confirmation',subtotal:'Products total',store:'Store',required:'Please complete the details'}};
function cartGroups(){var g={};CART.forEach(function(c){var p=byId(c.sid),b=p&&best(p);if(!p||!b)return;var k=b.store;if(!g[k])g[k]=[];g[k].push({c:c,p:p,b:b})});return g}
function orderRows(items){return items.map(function(x){var q=x.c.q,amount=x.b.price*q;return '<div class="order-item"><div><b>'+x.p.name+'</b><small>'+x.p.brand+(x.p.sz?' · '+x.p.sz:'')+'</small></div><span>'+q+' × '+x.b.price+' = '+amount.toFixed(2)+' '+(x.b.cur||'')+'</span></div>'}).join('')}
function cartHTML(){var l=LB[lang],u=ORDER_UI[lang],g=cartGroups(),stores=Object.keys(g);if(!stores.length)return '<p class="empty" style="text-align:center">'+T().she.cart+'</p>';var total=0,groups=stores.map(function(store){var items=g[store],sub=items.reduce(function(a,x){return a+x.b.price*x.c.q},0);total+=sub;return '<section class="cart-store"><div class="cart-store-head"><div><b>'+esc(store)+'</b><small>'+items.length+' '+u.store+'</small></div><button class="store-order-btn" data-order-store="'+esc(store)+'" aria-label="'+u.execute+'">'+u.execute+' <span>→</span></button></div>'+items.map(function(x){var q=x.c.q;return '<div class="cl"><div><b>'+x.p.name+'</b><small>'+x.p.brand+' · '+x.b.price+' '+(x.b.cur||'')+'</small></div><div class="cq"><button data-cq="'+x.c.sid+'|-1">−</button><span>'+q+'</span><button data-cq="'+x.c.sid+'|1">+</button></div><button class="x" data-cr="'+x.c.sid+'">×</button></div>'}).join('')+'<div class="store-subtotal"><span>'+u.subtotal+'</span><b>'+sub.toFixed(2)+' '+(items[0].b.cur||'')+'</b></div></section>'}).join('');return '<div class="cart-groups">'+groups+'</div><div class="ct"><span>'+l.total+'</span><b>'+total.toFixed(2)+'</b></div><small class="tn">'+l.taxnote+' '+u.pending+'</small>'}
function orderFormHTML(store){var u=ORDER_UI[lang],items=cartGroups()[store]||[],sub=items.reduce(function(a,x){return a+x.b.price*x.c.q},0),now=new Date(),num='ELN-'+now.getFullYear()+String(now.getMonth()+1).padStart(2,'0')+String(now.getDate()).padStart(2,'0')+'-'+Date.now().toString().slice(-6);return '<div class="order-form-wrap"><button class="back-cart" data-back-cart>← '+u.back+'</button><h3>'+u.orderTitle+'</h3><div class="order-meta"><span>'+u.store+': <b>'+esc(store)+'</b></span><span>'+u.orderNo+': <b>'+num+'</b></span></div><div class="order-summary">'+orderRows(items)+'<div class="store-subtotal"><span>'+u.subtotal+'</span><b>'+sub.toFixed(2)+' '+(items[0]&&items[0].b.cur||'')+'</b></div></div><form data-store-order-form data-store="'+esc(store)+'" data-order-number="'+num+'"><input name="name" placeholder="'+u.name+'" required><input name="phone" type="tel" placeholder="'+u.phone+'" required><input name="email" type="email" placeholder="'+u.email+'"><textarea name="address" rows="3" placeholder="'+u.address+'" required></textarea><textarea name="notes" rows="2" placeholder="'+u.notes+'"></textarea><button class="btn" type="submit">'+u.confirm+'</button></form></div>'}
function closeSheet(){var s=document.getElementById('sheet');if(s)s.hidden=true;document.body.classList.remove('sheet-open')}
function openStoreOrder(store){if(!AUTH){PENDING_STORE=store;sheet('login');return}document.getElementById('sheetB').innerHTML=orderFormHTML(store);document.getElementById('sheet').hidden=false;document.body.classList.add('sheet-open')}
function readOrders(){var a=[];try{a=JSON.parse(localStorage.getItem('elan_orders')||'[]')}catch(e){}return a}
function saveOrders(a){try{localStorage.setItem('elan_orders',JSON.stringify(a))}catch(e){}}
function orderSnapshot(o){return{customer:{name:(o.customer&&o.customer.name)||'',phone:(o.customer&&o.customer.phone)||'',email:(o.customer&&o.customer.email)||'',address:(o.customer&&o.customer.address)||''},items:(o.items||[]).map(function(x){return{id:String(x.id),quantity:+x.quantity||0,unitPrice:+x.unitPrice||0,currency:x.currency||'',total:+x.total||0}}).sort(function(a,b){return a.id.localeCompare(b.id)}),subtotal:+o.subtotal||0,shipping:o.shipping==null?null:+o.shipping,total:o.total==null?null:+o.total}}
function compareOrder(first,second){var a=orderSnapshot(first),b=orderSnapshot(second),m=[];['name','phone','email','address'].forEach(function(k){if(a.customer[k]!==b.customer[k])m.push('customer.'+k)});if(a.subtotal!==b.subtotal)m.push('subtotal');if(a.shipping!=null&&b.shipping!=null&&a.shipping!==b.shipping)m.push('shipping');if(a.total!=null&&b.total!=null&&a.total!==b.total)m.push('total');if(a.items.length!==b.items.length)m.push('items.length');a.items.forEach(function(x,i){var y=b.items[i];if(!y||x.id!==y.id||x.quantity!==y.quantity||x.unitPrice!==y.unitPrice||x.currency!==y.currency||x.total!==y.total)m.push('items.'+x.id)});return{matched:!m.length,mismatches:m}}
function removeCompletedStoreItems(order){var ids={};(order.items||[]).forEach(function(x){ids[String(x.id)]=1});CART=CART.filter(function(c){return !ids[String(c.sid)]});saveCart()}
function restoreCancelledStoreItems(order){(order.items||[]).forEach(function(x){var id=String(x.id||x.productSizeId),it=CART.filter(function(c){return String(c.sid)==id})[0],q=+x.quantity||0;if(!q)return;if(it)it.q+=q;else CART.push({sid:id,q:q})});saveCart();cartPulse()}
function restoreCancelledStoreItemsFromToken(){var m=location.search.match(/[?&]restore_token=([^&]+)/);if(!m)return;fetch('/api/restore-store-order',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({restoreToken:decodeURIComponent(m[1])})}).then(function(r){return r.json()}).then(function(d){if(!d.ok||!Array.isArray(d.items))return;restoreCancelledStoreItems({items:d.items});toast(lang=='ar'?'تمت إعادة منتجات الطلب الملغى إلى سلتك':'Cancelled order items were restored to your cart');history.replaceState({},'',location.pathname)}).catch(function(){})}
function receiveStoreNotification(notification){var n=notification||{},tracking=n.trackingNumber||n.orderNumber||(n.order&& (n.order.trackingNumber||n.order.orderNumber));if(!tracking)return{matched:false,error:'missing_tracking_number'};var orders=readOrders(),order=orders.filter(function(x){return x.orderNumber==tracking||x.trackingNumber==tracking})[0];if(!order)return{matched:false,error:'order_not_found',trackingNumber:tracking};var storeOrder=n.order||n,result=compareOrder(order,storeOrder),status=String(n.status||'').toLowerCase(),success=['completed','success','succeeded','paid','confirmed'].indexOf(status)>-1,failed=['rejected','failed','cancelled','not_completed','declined'].indexOf(status)>-1;order.storeNotification={notificationType:'store_result',receivedAt:new Date().toISOString(),payload:n};order.reconciliation={trackingNumber:tracking,matched:result.matched,mismatches:result.mismatches,status:success?'completed':failed?'not_completed':'under_review'};order.status=success&&result.matched?'completed':failed?'store_cancelled':'needs_review';orders=orders.map(function(x){return x.orderNumber==order.orderNumber?order:x});saveOrders(orders);if(success&&result.matched)removeCompletedStoreItems(order);if(failed)restoreCancelledStoreItems(order);return order.reconciliation}
window.receiveStoreNotification=receiveStoreNotification;window.addEventListener('store-notification',function(e){receiveStoreNotification(e.detail)});
function persistOrderToSupabase(order){if(!SB.url||!SB.key||!order.storeId)return;var h={apikey:SB.key,Authorization:'Bearer '+(AUTH&&AUTH.access_token||SB.key),'Content-Type':'application/json'};fetch(SB.url+'/rest/v1/rpc/create_checkout_session',{method:'POST',headers:h,body:JSON.stringify({p_payload:{trackingNumber:order.trackingNumber,customer:order.customer,currency:order.currency,subtotal:order.subtotal}})}).then(function(r){return r.json()}).then(function(session){if(session&&session.id)order.checkoutSessionId=session.id;return fetch(SB.url+'/rest/v1/rpc/create_store_order_request',{method:'POST',headers:h,body:JSON.stringify({p_payload:order})})}).catch(function(){})}
function sendStoreOrder(form){var store=form.dataset.store,g=cartGroups(),items=g[store]||[],u=ORDER_UI[lang],order={orderNumber:form.dataset.orderNumber,trackingNumber:form.dataset.orderNumber,notificationType:'initial_order',store:store,storeId:(ST.filter(function(x){return x[0]==store})[0]||[])[2]||'',currency:(items[0]&&items[0].b.cur)||'EGP',customer:{name:form.elements.name.value.trim(),phone:form.elements.phone.value.trim(),email:form.elements.email.value.trim(),address:form.elements.address.value.trim(),notes:form.elements.notes.value.trim()},items:items.map(function(x){return{id:x.p.id,productSizeId:x.p.id,storeProductId:x.b.storeProductId||'',name:x.p.name,brand:x.p.brand,size:x.p.sz,quantity:x.c.q,unitPrice:x.b.price,currency:x.b.cur||'',total:+(x.b.price*x.c.q).toFixed(2)}}),subtotal:+items.reduce(function(a,x){return a+x.b.price*x.c.q},0).toFixed(2),shipping:null,total:null,status:'awaiting_store_confirmation',createdAt:new Date().toISOString()};var orders=readOrders();orders.push(order);saveOrders(orders);var out=[];try{out=JSON.parse(localStorage.getItem('elan_order_outbox')||'[]')}catch(e){}out.push(order);try{localStorage.setItem('elan_order_outbox',JSON.stringify(out))}catch(e){}persistOrderToSupabase(order);var endpoint=CFG.orderEndpoint||CFG.endpoint;if(endpoint)fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(order)}).catch(function(){});document.getElementById('sheetB').innerHTML='<div class="order-confirm"><h3>'+u.sent+'</h3><p>'+u.orderNo+': <b>'+order.orderNumber+'</b></p><p>'+u.saved+'</p><button class="btn" data-back-cart>'+u.back+'</button></div>'}
function taxNote(b,l){var a=[];if(b.tax===true)a.push(l.incTax);else if(b.tax===false)a.push(l.excTax);if(b.ship===true)a.push(l.incShip);else if(b.ship===false)a.push(l.excShip);return a.join(' \u00b7 ')}
function prodView(x,l,t){var p=byId(x.sid);if(!p)return '<p class="empty">'+l.none+'</p>';var b=best(p),sz=PERFUMES.filter(function(q){return q.pid==p.pid});
var img=p.img?'<img src="'+p.img+'" alt="">':'<div class="ph" style="width:60%"></div>';
var cats=(p.cats||[]).map(function(i){return nmOf('cats',i)}).join('\u060c '),occs=(p.occs||[]).map(function(i){return '<span class="tg">'+nmOf('occ',i)+'</span>'}).join(''),nts=(p.notes||[]).map(function(i){return '<span class="tg">'+nmOf('notes',i)+'</span>'}).join('');
var rel=PERFUMES.filter(function(q){return q.pid!=p.pid&&q.brand==p.brand}).filter(function(q,i,a){return a.findIndex(function(z){return z.pid==q.pid})==i}).slice(0,4);
return '<div class="pd"><div class="pdi">'+img+'</div><h2 class="pdn">'+(p.pn||p.name)+'</h2><p class="pdb">'+p.brand+(b?' \u00b7 '+b.store:'')+'</p>'+ratingHTML(p.rating)
+(sz.length>1?'<div class="szs">'+sz.map(function(q){var qb=best(q);return '<button class="sz'+(q.id==p.id?' on':'')+'" data-go="prod|'+q.id+'">'+(q.sz||'')+(qb?' \u00b7 '+qb.price:'')+'</button>'}).join('')+'</div>':(p.sz?'<p class="pdb">'+l.size+': '+p.sz+'</p>':''))
+(b?'<div class="pdp"><span class="price" style="font-size:24px">'+b.price+' '+(b.cur||'')+'</span><small>'+taxNote(b,l)+'</small></div><div class="qrow"><label for="qty">'+l.qty+'</label><input id="qty" type="number" min="1" value="1"'+(b.stock!=null?' max="'+b.stock+'"':'')+'>'+(b.stock!=null?'<small>'+l.availq+b.stock+'</small>':'')+'</div><button class="btn" data-add="'+p.id+'" data-q="qty">'+l.add+'</button>':'<span class="st">'+l.unav+'</span>')
+(cats?'<p class="pdr"><b>'+l.cat+':</b> '+cats+'</p>':'')+(occs?'<div class="pdr"><b>'+l.oc+':</b> <span class="tgs" style="display:inline-flex">'+occs+'</span></div>':'')
+(p.desc?'<h4 class="pdh">'+l.desc+'</h4><p class="pdt">'+p.desc+'</p>':'')+(p.comp?'<h4 class="pdh">'+l.comp+'</h4><p class="pdt">'+p.comp+'</p>':'')+(nts?'<h4 class="pdh">'+l.notes+'</h4><div class="tgs">'+nts+'</div>':'')+'</div>'
+(rel.length?'<h4 class="pdh" style="text-align:center;margin-top:24px">'+l.rel+'</h4><div class="grid">'+rel.map(function(q){return pc({p:q,b:best(q)})}).join('')+'</div>':'')}
function strip(id){var r=PERFUMES.map(function(p){return{p:p,b:best(p)}}).filter(function(x){return(x.b||id=='soon')&&x.p.offers.some(function(o){return(o.flags||[]).indexOf(id)>-1})}).slice(0,6);return r.length?r.map(pc).join(''):'<div class="empty">'+T().wait+'</div>'}
function featureScore(p,b,pool){var max={sales:1,searches:1,views:1,requests:1};pool.forEach(function(x){max.sales=Math.max(max.sales,x.p.sales||0);max.searches=Math.max(max.searches,x.p.searches||0);max.views=Math.max(max.views,x.p.views||0);max.requests=Math.max(max.requests,x.p.requests||0)});var distinction=(p.ind||[]).length?1:0;return ((p.sales||0)/max.sales)*.35+(Math.min(p.rating||0,5)/5)*.25+((p.searches||0)/max.searches)*.2+((p.views||0)/max.views)*.1+((p.requests||0)/max.requests)*.05+distinction*.05}
function topSectionCards(field,index,limit){var rows=PERFUMES.map(function(p){return{p:p,b:best(p)}}).filter(function(x){return x.b&&(x.p[field]||[]).indexOf(index)>-1}),unique={};rows.forEach(function(x){var key=x.p.pid||x.p.id;if(!unique[key]||x.b.price<unique[key].b.price)unique[key]=x});var pool=Object.keys(unique).map(function(k){return unique[k]});return pool.sort(function(a,b){return featureScore(b.p,b.b,pool)-featureScore(a.p,a.b,pool)||((b.p.sales||0)-(a.p.sales||0))||((b.p.rating||0)-(a.p.rating||0))}).slice(0,limit)}
function allSectionCards(field,count,perSection){var out=[],limit=perSection||6;for(var i=0;i<count;i++)out=out.concat(topSectionCards(field,i,limit));return out.slice(0,count*limit)}
function filterPanel(l){return '<details class="filter-panel"><summary class="filter-head"><b>'+(lang=='ar'?'تصفية العطور':'Refine fragrances')+'</b><span class="filter-summary">'+(lang=='ar'?'خيارات البحث':'Search options')+'</span><button type="button" data-filter-reset>'+(lang=='ar'?'إعادة ضبط':'Reset')+'</button></summary><div class="filter-body"><label class="filter-search"><span>⌕</span><input class="q" data-k="q" placeholder="'+l.s+'" value="'+F.q+'"></label><div class="filter-grid">'+sel('cat',l.cat,sec('cats')[3])+sel('br',l.br,BR.map(function(b){return{v:b,l:b}}))+sel('st',l.st,ST.map(function(s){return{v:s[0],l:s[0]}}))+sel('oc',l.oc,sec('occ')[3])+sel('nt',l.nt,sec('notes')[3])+'<input data-k="min" type="number" min="0" placeholder="'+l.pmin+'" value="'+F.min+'"><input data-k="max" type="number" min="0" placeholder="'+l.pmax+'" value="'+F.max+'"><select class="relevance-select" data-k="sort" aria-label="'+(lang=='ar'?'الأكثر صلة':'Most relevant')+'">'+l.so.map(function(o,i){return '<option value="'+i+'"'+(F.sort==i?' selected':'')+'>'+o+'</option>'}).join('')+'</select></div></div></details>'}

function ordersHTML(rows){if(!rows.length)return '<p class="empty" style="text-align:center">'+T().she.orders+'</p>';return '<div class="orders-list">'+rows.map(function(o){return '<article class="order-card"><div><b>'+esc(o.tracking_number||'—')+'</b><small>'+esc(o.customer_name||'')+'</small></div><span class="order-status">'+esc(o.status||'pending')+'</span><small>'+esc(o.created_at||'')+'</small></article>'}).join('')+'</div>'}
async function loadOrdersForSheet(){if(!AUTH||!SB.url||!SB.key)return;try{var r=await fetch(SB.url+'/rest/v1/store_order_requests?select=tracking_number,customer_name,status,created_at&order=created_at.desc&limit=50',{headers:authHeaders()});if(!r.ok)return;var rows=await r.json(),box=document.getElementById('sheetB');if(box&&!document.getElementById('sheet').hidden)box.innerHTML='<button class="sheet-close" type="button" data-close-sheet aria-label="'+(lang=='ar'?'إغلاق':'Close')+'">×</button><h3>'+T().sh.orders+'</h3>'+ordersHTML(rows)}catch(e){}}
function sheet(k){var t=T(),f=k=='login'||k=='signup',authLink=k=='login'?'signup':'login',body=f?'<form data-auth-form data-auth-mode="'+k+'" style="display:grid;gap:10px">'+(k=='signup'?'<input name="name" placeholder="'+t.nm+'" required>':'')+'<input name="email" type="email" placeholder="'+t.em+'" required><input name="password" type="password" placeholder="'+t.pw+'" minlength="6" required><button class="btn" type="submit">'+t.sh[k]+'</button><button type="button" class="back-cart" data-sheet="'+authLink+'">'+t.sh[authLink]+'</button></form>':k=='cart'?cartHTML():k=='orders'?'<p class="empty" style="text-align:center">'+t.she.orders+'</p>':'<p class="empty" style="text-align:center">'+t.she[k]+'</p>';document.getElementById('sheetB').innerHTML='<button class="sheet-close" type="button" data-close-sheet aria-label="'+(lang=='ar'?'إغلاق':'Close')+'">×</button><h3>'+t.sh[k]+'</h3>'+body;document.getElementById('sheet').hidden=false;document.body.classList.add('sheet-open');if(k=='orders')loadOrdersForSheet()}
function sendMsg(e){e.preventDefault();var f=e.target,r={kind:document.getElementById('kind').value,ts:Date.now()};f.querySelectorAll('[data-p]').forEach(function(i){r[i.dataset.p]=i.value});try{if(CFG.endpoint)fetch(CFG.endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(r)});else{var q=JSON.parse(localStorage.getItem('elan_outbox')||'[]');q.push(r);localStorage.setItem('elan_outbox',JSON.stringify(q))}}catch(x){}f.reset();alert(T().sent);return false}
document.addEventListener('submit',function(e){var af=e.target.closest('[data-auth-form]');if(af){e.preventDefault();if(!af.reportValidity())return;authSubmit(af);return}var f=e.target.closest('[data-store-order-form]');if(f){e.preventDefault();if(!f.reportValidity())return;sendStoreOrder(f)}});
document.addEventListener('click',function(e){var o=e.target.closest('[data-order-store]');if(o){openStoreOrder(o.dataset.orderStore);return}if(e.target.closest('[data-close-sheet]')){closeSheet();return}if(e.target.closest('[data-back-cart]')){sheet('cart');return}var h=e.target.closest('[data-sheet]');if(h){document.getElementById('menu').classList.remove('open');sheet(h.dataset.sheet)}else if(e.target.id=='sheet')closeSheet();else if(e.target.id=='mov')document.getElementById('menu').classList.remove('open')});
var ly=0;addEventListener('scroll',function(){var y=scrollY,b=document.body;b.classList.toggle('sc',y>innerHeight*.6);document.documentElement.style.setProperty('--p',Math.min(y/220,1));ly=y},{passive:true});
var HS=[{bg:'radial-gradient(circle at 30% 20%,#f9e9cf,#e9d3b0 45%,#c7a677)',c:'#fff',s:'#8a5e0c'},{bg:'linear-gradient(160deg,#f4efe6,#dcd3c2 60%,#b9ad96)',c:'#3a2f1c',s:'#f0e0b0'},{bg:'linear-gradient(170deg,#eaf0ee,#c9d8d2 55%,#9fb5ab)',c:'#fff',s:'#355248'}],hi=0;
function hero(){var h=HS[hi%HS.length],e=document.getElementById('hero');e.style.background=h.bg;e.style.setProperty('--hc',h.c);e.style.setProperty('--hs',h.s)}
function best(p){var o=p.offers.filter(function(x){return x.avail}).sort(function(a,b){return a.price-b.price});return o[0]||null}
function sec(id){return T().S.filter(function(s){return s[0]==id})[0]}
function lab(c){var l=LB[lang];return c.k=='home'?l.home:c.k=='sec'?(c.id=='all'?l.all2:sec(c.id)[1]):c.k=='col'?sec(c.id)[3][c.i]:c.k=='prod'?((byId(c.sid)||{}).pn||''):c.n}
function go(g){var a=g.split('|'),H={k:'home'},p=a[0];
P=p=='prod'?[H,{k:'sec',id:'all'},{k:'prod',sid:a[1]}]:p=='sec'?[H,{k:'sec',id:a[1]}]:p=='brand'?[H,{k:'sec',id:'brands'},{k:'brand',n:a[1]}]:p=='store'?[H,{k:'sec',id:'stores'},{k:'store',n:a[1]}]:[H,{k:'sec',id:a[1]},{k:'col',id:a[1],i:+a[2]}];
openP()}
function openP(){var x=P[P.length-1];F={q:'',cat:'',br:'',st:'',oc:'',nt:'',min:'',max:'',sort:0,sec:''};
if(x.k=='brand')F.br=x.n;if(x.k=='store')F.st=x.n;
if(x.k=='col'){var m={cats:'cat',occ:'oc',notes:'nt'};F[m[x.id]]=x.i}
if(x.k=='sec'&&{offers:1,new:1,master:1,soon:1}[x.id])F.sec=x.id;
document.body.classList.add('inner');scrollTo(0,0);view()}
function list(){var q=F.q.toLowerCase();return PERFUMES.map(function(p){return{p:p,b:best(p)}}).filter(function(x){var p=x.p;return (x.b||F.sec=='soon')&&(!q||(p.name+' '+p.brand).toLowerCase().indexOf(q)>-1)&&(F.br===''||p.brand==F.br)&&(F.st===''||p.offers.some(function(o){return o.avail&&o.store==F.st}))&&(F.cat===''||(p.cats||[]).indexOf(+F.cat)>-1)&&(F.oc===''||(p.occs||[]).indexOf(+F.oc)>-1)&&(F.nt===''||(p.notes||[]).indexOf(+F.nt)>-1)&&(F.min===''||(x.b||{price:0}).price>=+F.min)&&(F.max===''||(x.b||{price:0}).price<=+F.max)&&(!F.ind||(p.ind||[]).indexOf(F.ind)>-1)&&(!F.sec||p.offers.some(function(o){return(o.flags||[]).indexOf(F.sec)>-1}))}).sort([function(a,b){return(b.p.rel||0)-(a.p.rel||0)},function(a,b){return(b.p.ts||0)-(a.p.ts||0)},function(a,b){return ((a.b||{}).price||0)-((b.b||{}).price||0)},function(a,b){return ((b.b||{}).price||0)-((a.b||{}).price||0)}][F.sort])}
function results(){var l=LB[lang],r=list();document.getElementById('res').innerHTML=r.length?r.map(pc).join(''):'<div class="empty">'+l.none+'</div>'}
function sel(k,lbl,opts){return '<select data-k="'+k+'"><option value="">'+lbl+' — '+LB[lang].all+'</option>'+opts.map(function(o,i){var v=o.v!==undefined?o.v:i;return '<option value="'+v+'"'+(String(F[k])===String(v)?' selected':'')+'>'+(o.l||o)+'</option>'}).join('')+'</select>'}
function view(){var t=T(),l=LB[lang],x=P[P.length-1],V=document.getElementById('view');
var h='<nav class="bc">'+P.map(function(c,i){return i==P.length-1?'<b>'+lab(c)+'</b>':'<a data-bc="'+i+'">'+lab(c)+'</a>'}).join('<i>›</i>')+'</nav><h3>'+lab(x)+'</h3>';
if(x.k=='prod'){V.innerHTML=h.substring(0,h.indexOf('<h3>'))+prodView(x,l,t);return}var hub=x.k=='sec'&&{brands:1,stores:1,cats:1}[x.id];
if((x.k=='sec'||x.k=='col')&&(x.id=='cats'||x.id=='occ'||x.id=='notes')){var field=x.id=='cats'?'cats':x.id=='occ'?'occs':'notes',items=x.k=='sec'?allSectionCards(field,sec(x.id)[3].length,x.id=='cats'?10:6):topSectionCards(field,+x.i,30),cards=items.map(function(y){return pc(y)}).join('');h+='<div class="grid section-perfume-grid">'+(cards||'<div class="empty">'+l.none+'</div>')+'</div>';V.innerHTML=h;return}
if(hub){var c=x.id=='brands'?BR.map(function(b){return card('','<span class="gold" style="font-weight:700">'+b+'</span>','',t.wait,'brand|'+b)}):x.id=='stores'?ST.map(function(s){return card('wide','<b>'+s[0]+'</b>',s[1]||t.sdesc,t.status,'store|'+s[0])}):sec(x.id)[3].map(function(n,i){return card('round',n,'',t.view,'col|'+x.id+'|'+i,ART[x.id+i])});h+='<div class="grid">'+c.join('')+'</div>'}
else{
if(x.k=='store'){var su=ST.filter(function(s){return s[0]==x.n})[0],bs={};PERFUMES.forEach(function(p){p.offers.forEach(function(o){if(o.store==x.n&&o.avail)bs[p.brand]=1})});
h+='<div class="card wide" style="cursor:default;margin:10px auto;max-width:340px"><h4 class="en">'+x.n+'</h4><small>'+l.inf+'</small><span class="st">'+t.status+'</span><small>'+l.bs+': '+(Object.keys(bs).join(', ')||'—')+'</small></div>'}
h+=(x.id=='master'?chips():'')+filterPanel(l)+'<div id="res" class="grid"></div>'}
V.innerHTML=h;if(document.getElementById('res'))results()}
document.addEventListener('click',function(e){var reset=e.target.closest('[data-filter-reset]');if(reset){openP();return}var ad=e.target.closest('[data-add]');if(ad){e.preventDefault();var qi=ad.dataset.q?document.getElementById(ad.dataset.q):null;addToCart(ad.dataset.add,qi?+qi.value||1:1);return}var cq=e.target.closest('[data-cq]');if(cq){cartQty(cq.dataset.cq);return}var cr=e.target.closest('[data-cr]');if(cr){cartDel(cr.dataset.cr);return}var g=e.target.closest('[data-go]');if(g){go(g.dataset.go);return}var b=e.target.closest('[data-bc]');if(b){var i=+b.dataset.bc;if(!i){document.body.classList.remove('inner');scrollTo(0,0)}else{P=P.slice(0,i+1);openP()}}});
document.addEventListener('input',function(e){var k=e.target.dataset&&e.target.dataset.k;if(k){F[k]=k=='sort'?+e.target.value:e.target.value;results()}});document.addEventListener('change',function(e){var k=e.target.dataset&&e.target.dataset.k;if(k){F[k]=k=='sort'?+e.target.value:e.target.value;results()}});
var BR=['AMOUAGE','ARMAF','AFNAN','ASSAF','RASASI','FRENCH AVENUE','ARABIYAT PRESTIGE','LATTAFA','Maison Alhambra'];
var ST=[['Afnan Egypt',''],['Emarati Scents','']];var BR0=BR.slice();var SB={url:'',key:''},DSIG='',AUTH=null,PENDING_STORE='';try{AUTH=JSON.parse(localStorage.getItem('elan_auth_session')||'null')}catch(e){AUTH=null}
function authSubmit(form){if(!SB.url||!SB.key)return toast('تعذر الاتصال بخدمة الحساب');var mode=form.dataset.authMode,email=form.elements.email.value.trim(),password=form.elements.password.value,name=form.elements.name?form.elements.name.value.trim():'';var url=SB.url+'/auth/v1/'+(mode=='login'?'token?grant_type=password':'signup');fetch(url,{method:'POST',headers:{apikey:SB.key,'Content-Type':'application/json'},body:JSON.stringify(mode=='login'?{email:email,password:password}:{email:email,password:password,data:{full_name:name}})}).then(function(r){return r.json()}).then(async function(d){if(!d.access_token){toast(d.msg||'تعذر تسجيل الدخول');return}AUTH=d;try{localStorage.setItem('elan_auth_session',JSON.stringify(d))}catch(e){}if(window.GuestIdentity)await GuestIdentity.claim(d.access_token);await syncCartFromCloud(!CART_FIRST_SYNC_DONE);if(PENDING_STORE){var st=PENDING_STORE;PENDING_STORE='';openStoreOrder(st)}else sheet('cart')}).catch(function(){toast('تعذر الاتصال بخدمة الحساب')})}
async function loadData(){
try{
if(!SB.url){var c=await fetch('/api/config');if(!c.ok)return;SB=await c.json();if(!SB.url||!SB.key)return}
var g=function(p){return fetch(SB.url+'/rest/v1/'+p,{headers:{apikey:SB.key,Authorization:'Bearer '+SB.key}}).then(function(r){if(!r.ok)throw new Error(r.status);return r.json()})};
var d=await Promise.all([g('public_brands?select=name,slug'),g('public_stores?select=name,short_description'),g('public_products?select=id,name,brand_name,sales_count,views_count,search_count,request_count,average_rating,short_description,official_description,composition'),g('cheapest_offers?select=product_size_id,product_id,store_id,store_name,price,currency,stock_quantity,price_includes_tax,price_includes_shipping'),g('product_sizes?select=id,size_label'),g('site_settings?select=key,value'),g('product_images?select=product_id,image_url,is_primary'),g('product_categories?select=product_id,category_id'),g('categories?select=id,name'),g('product_occasions?select=product_id,occasion_id'),g('occasions?select=id,name'),g('product_notes?select=product_id,note_id'),g('aromatic_notes?select=id,name'),g('store_products?select=product_size_id&is_new_arrival=eq.true'),g('offers?select=product_size_id'),g('store_products?select=id,store_id,product_size_id')]);
var sig=JSON.stringify(d);if(sig==DSIG)return;DSIG=sig;
BR=d[0].map(function(x){return x.name}).sort(function(a,b){var i=BR0.indexOf(a),j=BR0.indexOf(b);return(i<0?99:i)-(j<0?99:j)});
ST=d[1].map(function(x){return[x.name,x.short_description||'',x.id]});
var pm={},sm={},sp={};d[2].forEach(function(p){pm[p.id]=p});d[4].forEach(function(z){sm[z.id]=z});d[15].forEach(function(x){sp[x.store_id+'|'+x.product_size_id]=x.id;SP_BY_ID[String(x.id)]=x.product_size_id});
var im={},cn={},on={},nn={},cp={},op={},np={};
d[6].forEach(function(r){var u=/^https:\/\//.test(r.image_url||'')?r.image_url:'';if(u&&(!im[r.product_id]||r.is_primary))im[r.product_id]=u});
d[8].forEach(function(r){cn[r.id]=r.name});d[10].forEach(function(r){on[r.id]=r.name});d[12].forEach(function(r){nn[r.id]=r.name});
var idx=function(k,nm){return D.ar.S.filter(function(z){return z[0]==k})[0][3].indexOf(nm)};
d[7].forEach(function(r){var i=idx('cats',cn[r.category_id]);if(i>-1)(cp[r.product_id]=cp[r.product_id]||[]).push(i)});
d[9].forEach(function(r){var i=idx('occ',on[r.occasion_id]);if(i>-1)(op[r.product_id]=op[r.product_id]||[]).push(i)});
d[11].forEach(function(r){var i=idx('notes',nn[r.note_id]);if(i>-1)(np[r.product_id]=np[r.product_id]||[]).push(i)});
var nw={},ofs={},topB={};d[13].forEach(function(r){nw[r.product_size_id]=1});d[14].forEach(function(r){if(r.product_size_id)ofs[r.product_size_id]=1});
d[2].forEach(function(p){var v=p.sales_count||0;if(v>0&&(!topB[p.brand_name]||v>topB[p.brand_name]))topB[p.brand_name]=v});
var indOf=function(p){var a=[];if(p.sales_count>0)a.push('sales');if(p.views_count>0)a.push('views');if(p.search_count>0)a.push('searches');if(p.request_count>0)a.push('demand');if(p.average_rating!=null)a.push('rating');if(p.sales_count>0&&topB[p.brand_name]==p.sales_count)a.push('topBrand');return a};
PERFUMES=d[3].filter(function(o){return pm[o.product_id]}).map(function(o){var p=pm[o.product_id],z=sm[o.product_size_id];return{id:o.product_size_id,pid:o.product_id,pn:esc(p.name),sz:z?esc(z.size_label):'',name:esc(p.name)+(z?' \u00b7 '+esc(z.size_label):''),brand:esc(p.brand_name),rating:+p.average_rating||0,sales:+p.sales_count||0,searches:+p.search_count||0,views:+p.views_count||0,requests:+p.request_count||0,sd:esc(p.short_description),desc:esc(p.official_description),comp:esc(p.composition),img:im[o.product_id]||'',cats:cp[o.product_id]||[],occs:op[o.product_id]||[],notes:np[o.product_id]||[],ind:indOf(p),rel:p.sales_count||0,ts:0,offers:[{store:esc(o.store_name),storeId:o.store_id,storeProductId:sp[o.store_id+'|'+o.product_size_id]||'',price:+o.price,cur:o.currency,avail:true,flags:(nw[o.product_size_id]?['new']:[]).concat(ofs[o.product_size_id]?['offers']:[],indOf(p).length?['master']:[]),stock:o.stock_quantity,tax:o.price_includes_tax,ship:o.price_includes_shipping}]}});
var m={};d[5].forEach(function(x){m[x.key]=x.value});
CFG.waNumber=m.whatsapp_number||'';CFG.email=m.contact_email||'';CFG.orderEndpoint=m.order_request_endpoint||'';CFG.social.facebook=m.facebook_url||'';CFG.social.instagram=m.instagram_url||'';CFG.social.tiktok=m.tiktok_url||'';
if(m.footer_tagline)FT.ar.ph=m.footer_tagline;if(m.developer_credit)FT.ar.cr=m.developer_credit;
refreshAll();if(AUTH){if(window.GuestIdentity)await GuestIdentity.claim(AUTH.access_token);await syncCartFromCloud(!CART_FIRST_SYNC_DONE)}else if(window.GuestIdentity&&GuestIdentity.enabled())await syncGuestCartFromCloud();
}catch(e){}
}
var FT={ar:{a:'تصفح',b:[['العلامات','#brands'],['المختارات','#master'],['قصتنا','#about']],c:'تابعنا',ct:'تواصل',cs:'خدمة العملاء',ph:'من الخليج، بروح عالمية',tm:'الشروط',pv:'الخصوصية',cr:'إنشاء وتطوير'},en:{a:'Explore',b:[['Brands','#brands'],['Selections','#master'],['Our Story','#about']],c:'Follow us',ct:'Contact',cs:'Customer service',ph:'From the Gulf, with a global soul',tm:'Terms',pv:'Privacy',cr:'Created and developed'}};
function footer18(t){var f=FT[lang];
var icons={
facebook:'<svg viewBox="0 0 24 24" aria-hidden="true"><path fill="#fff" d="M13.7 21v-7h2.35l.35-2.73H13.7V9.53c0-.79.22-1.33 1.36-1.33h1.46V5.76c-.25-.03-1.1-.1-2.08-.1-2.06 0-3.47 1.26-3.47 3.58v2.03H8.64V14h2.33v7z"/></svg>',
instagram:'<svg viewBox="0 0 24 24" aria-hidden="true"><path fill="#fff" d="M12 7.2A4.8 4.8 0 1 0 12 16.8 4.8 4.8 0 0 0 12 7.2zm0 7.92A3.12 3.12 0 1 1 12 8.88a3.12 3.12 0 0 1 0 6.24zM17.76 6.96a1.12 1.12 0 1 1-2.24 0 1.12 1.12 0 0 1 2.24 0zM12 2.4c-2.6 0-2.93.01-3.96.06-1.02.05-1.72.21-2.33.45a4.7 4.7 0 0 0-1.7 1.1 4.7 4.7 0 0 0-1.1 1.7c-.24.61-.4 1.31-.45 2.33C2.41 9.07 2.4 9.4 2.4 12s.01 2.93.06 3.96c.05 1.02.21 1.72.45 2.33a4.7 4.7 0 0 0 1.1 1.7 4.7 4.7 0 0 0 1.7 1.1c.61.24 1.31.4 2.33.45 1.03.05 1.36.06 3.96.06s2.93-.01 3.96-.06c1.02-.05 1.72-.21 2.33-.45a4.7 4.7 0 0 0 1.7-1.1 4.7 4.7 0 0 0 1.1-1.7c.24-.61.4-1.31.45-2.33.05-1.03.06-1.36.06-3.96s-.01-2.93-.06-3.96c-.05-1.02-.21-1.72-.45-2.33a4.7 4.7 0 0 0-1.1-1.7 4.7 4.7 0 0 0-1.7-1.1c-.61-.24-1.31-.4-2.33-.45C14.93 2.41 14.6 2.4 12 2.4zm0 1.68c2.56 0 2.86.01 3.86.06.93.04 1.44.2 1.78.33.45.17.77.38 1.1.72.34.33.55.65.72 1.1.13.34.29.85.33 1.78.05 1 .06 1.3.06 3.86s-.01 2.86-.06 3.86c-.04.93-.2 1.44-.33 1.78-.17.45-.38.77-.72 1.1-.33.34-.65.55-1.1.72-.34.13-.85.29-1.78.33-1 .05-1.3.06-3.86.06s-2.86-.01-3.86-.06c-.93-.04-1.44-.2-1.78-.33a2.96 2.96 0 0 1-1.1-.72 2.96 2.96 0 0 1-.72-1.1c-.13-.34-.29-.85-.33-1.78-.05-1-.06-1.3-.06-3.86s.01-2.86.06-3.86c.04-.93.2-1.44.33-1.78.17-.45.38-.77.72-1.1.33-.34.65-.55 1.1-.72.34-.13.85-.29 1.78-.33 1-.05 1.3-.06 3.86-.06z"/></svg>',
tiktok:'<svg viewBox="0 0 24 24" aria-hidden="true"><path fill="#fff" d="M15.65 3h2.6c.21 1.36.9 2.4 2.1 3.13v2.75a7.75 7.75 0 0 1-2.14-.53v6.1A5.55 5.55 0 1 1 12.66 9v2.82a2.77 2.77 0 1 0 2.77 2.63V3.85z"/></svg>'
};
var soIcon=['facebook','instagram','tiktok'].map(function(k){var u=CFG.social[k],label=k==='facebook'?'Facebook':k==='instagram'?'Instagram':'TikTok',cls=k==='facebook'?'si-fb':k==='instagram'?'si-ig':'si-tt';return /^https?:\/\//.test(u||'')?'<a class="'+cls+'" href="'+esc(u)+'" target="_blank" rel="noopener" aria-label="'+label+'">'+icons[k]+'</a>':'<span class="'+cls+'" aria-label="'+label+'">'+icons[k]+'</span>'}).join('');
var soText=['Facebook','Instagram','TikTok'].map(function(n){var u=CFG.social[n.toLowerCase()];return /^https?:\/\//.test(u||'')?'<a href="'+esc(u)+'" target="_blank" rel="noopener">'+n+'</a>':'<span>'+n+'</span>'}).join('');
var em=CFG.email?'<a href="mailto:'+esc(CFG.email)+'">'+esc(CFG.email)+'</a>':'<span>hello@gulfelan.example</span>';
var wd=String(CFG.waNumber||'').replace(/\D/g,''),cs=wd?'<a href="https://wa.me/'+wd+'" target="_blank" rel="noopener">'+f.cs+'</a>':'<span>'+f.cs+'</span>';
document.getElementById('fcols').innerHTML='<div><h5>'+f.a+'</h5>'+f.b.map(function(x){return '<a href="'+x[1]+'" onclick="document.body.classList.remove(\'inner\')">'+x[0]+'</a>'}).join('')+'<h5 style="margin-top:16px">'+f.c+'</h5>'+soText+'</div><div class="fgap"></div><div><h5>'+f.ct+'</h5>'+em+cs+'</div>';
document.getElementById('fph').innerHTML='<div class="fsocial">'+soIcon+'</div>'+esc(f.ph);
document.getElementById('fbar').innerHTML='<span>\u00a9 \u00c9lan Scents 2026</span><span>'+f.tm+'</span><span>'+f.pv+'</span>';
document.getElementById('fcr').innerHTML='<span>'+(lang=='ar'?'الانشاء والتطوير':'Created and developed')+'</span><img class="growthmark-img" src="/assets/growthmark.png" alt="GrowthMark"><small>'+(lang=='ar'?'الوكيل الرسمى للاعلان والتسويق':'Official Advertising & Marketing Agency')+'</small>'}
function T(){return D[lang]}
function card(cls,h,s,st,go,art){return '<div class="card '+cls+(art?' art':'')+'"'+(go?' data-go="'+go+'"':'')+'>'+(art?'<div class="artbg">'+art+'</div>':'')+'<h4 class="en" style="font-size:16px">'+h+'</h4>'+(s?'<small>'+s+'</small>':'')+(st?'<span class="st">'+st+'</span>':'')+'</div>'}
function render(){
var t=T();document.documentElement.lang=lang;document.documentElement.dir=lang=='ar'?'rtl':'ltr';
document.getElementById('barT').textContent=(t.bar).repeat(4);
document.querySelectorAll('[data-i]').forEach(function(e){e.textContent=t[e.dataset.i]});
document.querySelectorAll('[data-p]').forEach(function(e){e.placeholder=t[e.dataset.p]});
document.getElementById('lg').textContent=lang=='ar'?'EN':'ع';
var x=t.abx,c=x.cta.split(' Élan Scents… ');document.getElementById('abIn').innerHTML='<p>'+x.a+'</p><p>'+x.b+'</p><i class="orn"></i><p class="ab-hl gold">'+x.hl+'</p><p>'+x.c+'</p><p>'+x.d.replace('%L','<a class="ab-link" href="#occ">«'+x.link+'»</a>')+'</p><i class="orn"></i><div class="chips">'+t.pillars.split(' • ').map(function(c){return '<span>'+c+'</span>'}).join('')+'</div><p class="quote gold">'+t.q+'</p><div class="disc"><h4 class="gold">'+c[0]+'</h4><h4 class="gold">Élan Scents…</h4><p>'+c[1]+'</p><button class="btn" data-go="sec|all">'+t.view+'</button></div>';
document.getElementById('kind').innerHTML=t.kinds.map(function(k,i){return '<option value="'+k+'">'+k+'</option>'}).join('');
document.getElementById('fch').innerHTML=[['WhatsApp',CFG.waNumber],['Phone',CFG.phone],['Email',CFG.email]].map(function(c){return '<div><b>'+c[0]+'</b><span>'+(c[1]||'Coming soon')+'</span></div>'}).join('');
var navSections={2:'brands',3:'offers',4:'new',5:'master',6:'cats',7:'occ',8:'notes',9:'stores'},m=document.getElementById('menu');m.innerHTML=XBTN+t.menu.map(function(x,i){return (i==0?LOGO:i==1?'<a data-go="sec|all">'+x+'</a>':i==10?'<a href="/account.html">'+x+'</a>':i>=13?'<a data-sheet="'+(i==13?'login':'signup')+'">'+x+'</a>':'<a href="#'+(navSections[i]||(i==11?'about':i==12?'contact':''))+'">'+x+'</a>')}).join('');
m.onclick=function(e){m.classList.remove('open');if(!e.target.closest('.mx'))document.body.classList.remove('inner')};
footer18(t);counts();
var h='';
t.S.forEach(function(s){
var inner='';
if(s[2]=='b')inner=BR.map(function(b){return card('','<span class="gold" style="font-weight:700">'+b+'</span>','',t.wait,'brand|'+b)}).join('');
else if(s[2]=='r')inner=s[3].map(function(n,i){return card('round',n,'',t.view,'col|'+s[0]+'|'+i,ART[s[0]+i])}).join('');
else if(s[2]=='s')inner=ST.map(function(x){return card('wide','<div class="ph"></div><b>'+x[0]+'</b>',(x[1]||t.sdesc),t.status,'store|'+x[0])}).join('');
else inner=strip(s[0]);
h+='<section id="'+s[0]+'"><h3'+(s[0]=='master'?' class="gold en"':'')+'>'+s[1]+'</h3><span class="sub" data-go="sec|'+s[0]+'"'+(s[0]=='cats'||s[0]=='master'||s[0]=='notes'||s[0]=='occ'?' style="display:none"':'')+'>'+(s[0]=='notes'?t.explore:t.view)+'</span>'+(s[0]=='cats'?catBlocks():s[0]=='master'?masterBlock():'<div class="strip">'+inner+'</div>')+'</section>';
});
document.getElementById('main').innerHTML=h;
}
document.getElementById('lg').onclick=function(){lang=lang=='ar'?'en':'ar';render();if(P.length)view()};
function quickSearchResults(q){var box=document.getElementById('quickSearchResults');if(!box)return;q=q.trim().toLowerCase();if(!q){box.innerHTML='';box.hidden=true;return}var hits=PERFUMES.filter(function(p){return(p.name+' '+p.brand).toLowerCase().indexOf(q)>-1}).slice(0,6);box.innerHTML=hits.length?hits.map(function(p){var b=best(p);return '<button class="quick-item" data-quick-id="'+p.id+'"><span>'+p.name+'</span><small>'+p.brand+(b?' · '+b.price+' '+(b.cur||''):'')+'</small></button>'}).join(''):'<div class="quick-empty">'+LB[lang].none+'</div>';box.hidden=false}
function closeQuickSearch(){var w=document.getElementById('quickSearch');if(w)w.hidden=true}
var qsw=document.getElementById('quickSearch'),qsi=document.getElementById('quickSearchInput');
if(qsw&&qsi){qsi.placeholder=LB[lang].s;document.getElementById('quickSearchBtn').onclick=function(){qsw.hidden=!qsw.hidden;if(!qsw.hidden){qsi.placeholder=LB[lang].s;qsi.focus()}};qsi.oninput=function(){quickSearchResults(qsi.value)};document.getElementById('quickSearchForm').onsubmit=function(e){e.preventDefault();var q=qsi.value.trim();if(!q)return;closeQuickSearch();go('sec|all');F.q=q;view()}}
document.addEventListener('click',function(e){if(qsw&&!qsw.hidden&&!e.target.closest('#quickSearch')&&!e.target.closest('#quickSearchBtn'))closeQuickSearch()});
document.addEventListener('keydown',function(e){if(e.key==='Escape'){closeQuickSearch();closeSheet()}});
document.addEventListener('click',function(e){var item=e.target.closest('[data-quick-id]');if(item){closeQuickSearch();go('prod|'+item.dataset.quickId)}});
document.getElementById('mb').onclick=function(){document.getElementById('menu').classList.toggle('open')};
// 3D shadow on proximity of pointer/finger
function prox(e){var p=e.touches?e.touches[0]:e;document.querySelectorAll('.card').forEach(function(c){var r=c.getBoundingClientRect(),dx=Math.max(r.left-p.clientX,0,p.clientX-r.right),dy=Math.max(r.top-p.clientY,0,p.clientY-r.bottom);c.classList.toggle('near',Math.hypot(dx,dy)<60)})}
addEventListener('mousemove',prox);addEventListener('touchmove',prox,{passive:true});
hero();setInterval(function(){hi++;hero()},8000);render();cartBadge();loadData();setInterval(function(){if(AUTH&&!document.hidden){if(CART_LOCAL_DIRTY)pushCartToCloud();else syncCartFromCloud(!CART_FIRST_SYNC_DONE)}},5000);setTimeout(restoreCancelledStoreItemsFromToken,1200);setInterval(loadData,60000);
