create table if not exists public.checkout_sessions (
  id uuid primary key default gen_random_uuid(), tracking_number text not null unique, user_id uuid references auth.users(id), customer_name text not null, customer_phone text not null, customer_email text, customer_address text not null, status text not null default 'open' check (status in ('open','transferred','partially_cancelled','completed','closed','needs_review')), currency text not null default 'EGP', subtotal numeric(12,2) not null default 0 check (subtotal >= 0), shipping_amount numeric(12,2), total_amount numeric(12,2), created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
alter table public.store_order_requests add column if not exists checkout_session_id uuid references public.checkout_sessions(id);
create index if not exists checkout_sessions_user_idx on public.checkout_sessions(user_id, created_at desc);
create index if not exists store_order_requests_session_idx on public.store_order_requests(checkout_session_id, created_at desc);
alter table public.checkout_sessions enable row level security;
create policy checkout_sessions_admin_all on public.checkout_sessions for all to authenticated using (private.is_platform_admin()) with check (private.is_platform_admin());
create policy checkout_sessions_owner_read on public.checkout_sessions for select to authenticated using (user_id = auth.uid());
create policy checkout_sessions_owner_update on public.checkout_sessions for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create or replace function public.create_checkout_session(p_payload jsonb) returns jsonb language plpgsql security definer set search_path = public, private as $$ declare v_session public.checkout_sessions; v_user uuid := auth.uid(); begin if coalesce(trim(p_payload->'customer'->>'name'),'')='' or coalesce(trim(p_payload->'customer'->>'phone'),'')='' or coalesce(trim(p_payload->'customer'->>'address'),'')='' then raise exception 'Customer details are required'; end if; insert into public.checkout_sessions (tracking_number,user_id,customer_name,customer_phone,customer_email,customer_address,currency,subtotal) values (p_payload->>'trackingNumber',v_user,trim(p_payload->'customer'->>'name'),trim(p_payload->'customer'->>'phone'),nullif(trim(p_payload->'customer'->>'email'),''),trim(p_payload->'customer'->>'address'),coalesce(nullif(p_payload->>'currency',''),'EGP'),coalesce((p_payload->>'subtotal')::numeric,0)) returning * into v_session; return jsonb_build_object('id',v_session.id,'trackingNumber',v_session.tracking_number,'status',v_session.status); end; $$;
revoke all on function public.create_checkout_session(jsonb) from public;
grant execute on function public.create_checkout_session(jsonb) to authenticated;
alter table public.store_order_requests drop constraint if exists store_order_requests_status_check;
alter table public.store_order_requests add constraint store_order_requests_status_check check (status in ('awaiting_store_confirmation','store_confirmed','processing','shipped','delivered','store_rejected','store_cancelled','needs_review','completed','cancelled'));
